#!/bin/bash

save_file() {
  local filename="$1"
  local fdir=$(dirname "$filename")
  local fbase=$(basename "$filename")
  if [ -s "$filename" ]; then
    local FDSTAMP="$(date "+%y%m%d")"
    local FNUM=1
    while [ -s "$fdir/$fbase.${FDSTAMP}-${FNUM}" ]; do
      ((FNUM++))
    done
    mv "$filename" "$fdir/$fbase.${FDSTAMP}-${FNUM}"
  fi
}

if [ -z "$1" ] || [ ! -f "$1" ] || [ -n "$2" ]; then
  printf "save_file requires a filename as the first and only argument.\n"
  exit 1
fi

save_file "$1"

exit 0
